openapi: 3.0.0
info:
  title: AssesmenWebService
  version: 1.0.0
servers:
  - url: http://localhost:8080
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /regis:
    post:
      tags:
        - default
      summary: UserRegis
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: audya
                email: audy@gmail.com
                password: audy123
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - default
      summary: UserLogin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: audya
                password: audy123
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /pelukis:
    post:
      tags:
        - default
      summary: PelukisPost
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama: Dina
                alamat: Carawali
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: Pelukis
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /pelukis/{id}:
    put:
      tags:
        - default
      summary: PelukisUpdate
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID pelukis yang ingin diperbarui
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama: Egi
                alamat: Cokro
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: PelukisDelete
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID pelukis yang ingin dihapus
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /karya:
    get:
      tags:
        - default
      summary: Karya
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: KaryaPost
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                judul: audyardhaCanvas
                pelukis_id: 6
                tahun_dibuat: 2022
                media: Canvas Audy
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /karya/{id}:
    put:
      tags:
        - default
      summary: KaryaUpdate
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID karya yang ingin diperbarui
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                judul: nasywa lukis
                pelukis_id: 3
                tahun_dibuat: 2020
                media: Lukis dan gambar
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: KaryaDelete
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID karya yang ingin dihapus
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
